// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kennel.Migrations
{
    [DbContext(typeof(KennelDb))]
    [Migration("20260508142843_AddIncompatibilities")]
    partial class AddIncompatibilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Name", "OwnerId")
                        .IsUnique();

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Domain.Kennel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kennels");
                });

            modelBuilder.Entity("GoogleConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GoogleConnections");
                });

            modelBuilder.Entity("Incompatibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DogId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DogId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DogId1");

                    b.HasIndex("DogId2");

                    b.ToTable("Incompatibilities");
                });

            modelBuilder.Entity("Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("KennelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KennelId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Dog", b =>
                {
                    b.HasOne("Owner", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Incompatibility", b =>
                {
                    b.HasOne("Dog", "Dog1")
                        .WithMany()
                        .HasForeignKey("DogId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dog", "Dog2")
                        .WithMany()
                        .HasForeignKey("DogId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog1");

                    b.Navigation("Dog2");
                });

            modelBuilder.Entity("Occupation", b =>
                {
                    b.HasOne("Domain.Kennel", "Kennel")
                        .WithMany()
                        .HasForeignKey("KennelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reservation", "Reservation")
                        .WithMany("Occupations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kennel");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.HasOne("Dog", "Dog")
                        .WithMany("Reservations")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("Dog", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Owner", b =>
                {
                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Navigation("Occupations");
                });
#pragma warning restore 612, 618
        }
    }
}
